// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdwNb4kqcPw1BZlYOLUh65z6E--4fyIl4',
    appId: '1:1025130789348:web:040bfc29755063449deff1',
    messagingSenderId: '1025130789348',
    projectId: 'alarmapp-38064',
    authDomain: 'alarmapp-38064.firebaseapp.com',
    storageBucket: 'alarmapp-38064.firebasestorage.app',
    measurementId: 'G-1F63YEJK3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-jpIMaDlS5sexUzIgIeCdC_oIhzdGq90',
    appId: '1:1025130789348:android:e4304c172d3eb6e39deff1',
    messagingSenderId: '1025130789348',
    projectId: 'alarmapp-38064',
    storageBucket: 'alarmapp-38064.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR9X7ma3Zh6r6yXKiYP2lcjl4JXwlJEJE',
    appId: '1:1025130789348:ios:ef68b5e152c9bfa39deff1',
    messagingSenderId: '1025130789348',
    projectId: 'alarmapp-38064',
    storageBucket: 'alarmapp-38064.firebasestorage.app',
    iosBundleId: 'com.telalarm.wakeupcall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR9X7ma3Zh6r6yXKiYP2lcjl4JXwlJEJE',
    appId: '1:1025130789348:ios:ef68b5e152c9bfa39deff1',
    messagingSenderId: '1025130789348',
    projectId: 'alarmapp-38064',
    storageBucket: 'alarmapp-38064.firebasestorage.app',
    iosBundleId: 'com.telalarm.wakeupcall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdwNb4kqcPw1BZlYOLUh65z6E--4fyIl4',
    appId: '1:1025130789348:web:519e24d6263b4c609deff1',
    messagingSenderId: '1025130789348',
    projectId: 'alarmapp-38064',
    authDomain: 'alarmapp-38064.firebaseapp.com',
    storageBucket: 'alarmapp-38064.firebasestorage.app',
    measurementId: 'G-Q50FWBGLWM',
  );
}
